# Data Manipulation with Numpy

In [1]:
import numpy as np

In [4]:
group_1 = np.arange(1, 46)
group_2 = np.arange(46, 91)

print(group_1, end='\n\n')
print(group_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]

[46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69
 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]


In [5]:
group_1.shape

(45,)

In [7]:
group_3 = np.hstack((group_1, group_2))
group_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [8]:
group_3.shape

(90,)

In [12]:
group_3[:3]

array([1, 2, 3])

### np.hstack [doc](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)

```Python
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])
```

In [15]:
group_4 = np.vstack((group_1, group_2))
group_4[:, :3]

array([[ 1,  2,  3],
       [46, 47, 48]])

In [16]:
group_4.shape

(2, 45)

In [17]:
a = np.arange(10)
b = np.arange(10, 15)
a.resize(5, 2)
b.resize(5, 1)

In [19]:
np.concatenate((a, b), axis=1)

array([[ 0,  1, 10],
       [ 2,  3, 11],
       [ 4,  5, 12],
       [ 6,  7, 13],
       [ 8,  9, 14]])

In [30]:
heights = np.array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]).reshape(-1, 1)
ages = np.array([57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]).reshape(-1, 1)

In [32]:
height_age = np.hstack((heights, ages))
height_age

array([[189,  57],
       [170,  61],
       [189,  57],
       [163,  57],
       [183,  58],
       [171,  57],
       [185,  61],
       [168,  54],
       [173,  68],
       [183,  51],
       [173,  49],
       [173,  64],
       [175,  50],
       [178,  48],
       [183,  65],
       [193,  52],
       [178,  56],
       [173,  46],
       [174,  54],
       [183,  49],
       [183,  51],
       [180,  47],
       [168,  55],
       [180,  55],
       [170,  54],
       [178,  42],
       [182,  51],
       [180,  56],
       [183,  55],
       [178,  51],
       [182,  54],
       [188,  51],
       [175,  60],
       [179,  62],
       [183,  43],
       [193,  55],
       [182,  56],
       [183,  61],
       [177,  52],
       [185,  69],
       [188,  64],
       [188,  46],
       [182,  54],
       [185,  47],
       [191,  70]])

In [33]:
height_age.shape

(45, 2)

In [36]:
inch_height = height_age[:, 0] * 0.0328084
inch_height

array([6.2007876, 5.577428 , 6.2007876, 5.3477692, 6.0039372, 5.6102364,
       6.069554 , 5.5118112, 5.6758532, 6.0039372, 5.6758532, 5.6758532,
       5.74147  , 5.8398952, 6.0039372, 6.3320212, 5.8398952, 5.6758532,
       5.7086616, 6.0039372, 6.0039372, 5.905512 , 5.5118112, 5.905512 ,
       5.577428 , 5.8398952, 5.9711288, 5.905512 , 6.0039372, 5.8398952,
       5.9711288, 6.1679792, 5.74147  , 5.8727036, 6.0039372, 6.3320212,
       5.9711288, 6.0039372, 5.8070868, 6.069554 , 6.1679792, 6.1679792,
       5.9711288, 6.069554 , 6.2664044])

In [37]:
meters_height = height_age[:, 0] / 100
meters_height

array([1.89, 1.7 , 1.89, 1.63, 1.83, 1.71, 1.85, 1.68, 1.73, 1.83, 1.73,
       1.73, 1.75, 1.78, 1.83, 1.93, 1.78, 1.73, 1.74, 1.83, 1.83, 1.8 ,
       1.68, 1.8 , 1.7 , 1.78, 1.82, 1.8 , 1.83, 1.78, 1.82, 1.88, 1.75,
       1.79, 1.83, 1.93, 1.82, 1.83, 1.77, 1.85, 1.88, 1.88, 1.82, 1.85,
       1.91])

In [39]:
height_age.sum()

10575

In [40]:
height_age.sum(axis=0)

array([8100, 2475])

In [41]:
height_age.sum(axis=1)

array([246, 231, 246, 220, 241, 228, 246, 222, 241, 234, 222, 237, 225,
       226, 248, 245, 234, 219, 228, 232, 234, 227, 223, 235, 224, 220,
       233, 236, 238, 229, 236, 239, 235, 241, 226, 248, 238, 244, 229,
       254, 252, 234, 236, 232, 261])

we might be interested in only those presidents who started their presidency younger than 55 years old.

In [45]:
height_age[:, 1] < 55

array([False, False, False, False, False, False, False,  True, False,
        True,  True, False,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True,  True, False, False,  True, False,
       False, False,  True, False, False,  True,  True,  True, False])

In [44]:
height_age[height_age[:, 1] < 55]  # using mask

array([[168,  54],
       [183,  51],
       [173,  49],
       [175,  50],
       [178,  48],
       [193,  52],
       [173,  46],
       [174,  54],
       [183,  49],
       [183,  51],
       [180,  47],
       [170,  54],
       [178,  42],
       [182,  51],
       [178,  51],
       [182,  54],
       [188,  51],
       [183,  43],
       [177,  52],
       [188,  46],
       [182,  54],
       [185,  47]])

In [47]:
(height_age[:, 1] < 55).sum()

22

In [48]:
mask = height_age[:, 0] >= 186
mask.sum()

8

In [50]:
tall_presidents = height_age[mask]
tall_presidents

array([[189,  57],
       [189,  57],
       [193,  52],
       [188,  51],
       [193,  55],
       [188,  64],
       [188,  46],
       [191,  70]])

In [52]:
mask = (height_age[:, 0] >= 186) & (height_age[:, 1] <= 50)
mask.sum()

1

In [53]:
height_age[mask]

array([[188,  46]])

# Task 1

### Data Science - Average of Rows


In a matrix, or 2-d array X, the averages (or means) of the elements of rows is called row means.

**Task**
Given a 2D array, return the rowmeans.

**Input Format**
First line: two integers separated by spaces, the first indicates the rows of matrix X (n) and the second indicates the columns of X (p)
Next n lines: values of the row in X

**Output Format**
An numpy 1d array of values rounded to the second decimal.

```Python
2 2
1.5 1
2 2.9
```

**Sample Output**
[1.25 2.45]

**Explanation**
The first row has two numbers 1.5 and 1, thus the sum is 1.5 + 1 = 2.5 and the mean is then 2.5/2 = 1.25. Then for the second row, the average is calculated as (2 + 2.9)/2 = 4.9/2 = 2.45.

### My solution:
```Python
import numpy as np

fix = lambda x: list(map(float, x.split()))

dimension = fix(input())
n, p = [int(i) for i in dimension]

numbers_array = np.array([fix(input()) for _ in range(n)])

rounded = np.around(numbers_array.sum(axis=1) / p, 2)
print(rounded)
```